### ISSUE TITLE
T66y用了异步加载，怎么规避的啊

### ISSUE THREAD

**Issue by yeluoge26** [yikesoftware/t66y_spider#4]
之前写的爬虫，爬出来都是空地址，js做了异步加载，代码里面没看到怎么绕过的哦，麻烦问下如何绕过了

**Comment by yikesoftware** [comment]
好像我没遇到过反爬的问题，用beautifulsoup解析出来网页就可以抓到图床地址了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"yeluoge26"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月8日(星期三) 凌晨0:27
收件人:&nbsp;"yikesoftware/t66y_spider"<t66y_spider@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[yikesoftware/t66y_spider] T66y用了异步加载，怎么规避的啊 (#4)





 
之前写的爬虫，爬出来都是空地址，js做了异步加载，代码里面没看到怎么绕过的哦，麻烦问下如何绕过了

**Comment by yeluoge26** [comment]
> 好像我没遇到过反爬的问题，用beautifulsoup解析出来网页就可以抓到图床地址了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"yeluoge26"<notifications@github.com&gt;; 发送时间:&nbsp;2020年4月8日(星期三) 凌晨0:27 收件人:&nbsp;"yikesoftware/t66y_spider"<t66y_spider@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;[yikesoftware/t66y_spider] T66y用了异步加载，怎么规避的啊 (#4) 之前写的爬虫，爬出来都是空地址，js做了异步加载，代码里面没看到怎么绕过的哦，麻烦问下如何绕过了 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我之前能解析出来所有的图标地址都是空的，改了js，可能是改回来了，我去找找原来的的代码跑一下看，谢谢啦
